# Generated by Django 2.2.13 on 2020-06-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='testspec',
            name='vb123',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
